version: "3.9"
services:
  db:
    image: "postgres:14.4"
    restart: always
    container_name: "pipeline_postgres"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "54323:5432"
    volumes:
      - pipeline_postgres_data:/var/lib/postgresql/data
  web:
    build: .
    environment:
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432   
    container_name: "opub_pipeline"
    command: bash -c "chmod +x /code/start.sh && /code/start.sh"
    volumes:
      - .:/code
    ports:
      - "8003:8003"
      - "4200:4200"
      - "15671:15671" 
      - "15672:15672"
      - "25671:25671"
      - "25672:25672"
    depends_on:
      - db
volumes:
  pipeline_postgres_data:
    name: pipeline_postgres_data
